# Generated by Django 4.1.2 on 2023-03-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_post_profile_user_detail_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
