# Generated by Django 4.1.2 on 2023-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_post_is_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who_has',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
