# Generated by Django 4.1.2 on 2023-03-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_post_who_has"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="is_buy",
            field=models.IntegerField(default=0),
        ),
    ]
