# Generated by Django 4.1.2 on 2023-04-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_post_last_uuid_alter_post_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="last_uuid",
        ),
    ]
