# Generated by Django 4.1.2 on 2023-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_remove_post_last_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="in_sales",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
