# Generated by Django 4.1.2 on 2023-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_post_in_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="old_price",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
