# Generated by Django 4.1.2 on 2023-04-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_remove_post_in_sales_remove_post_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_buy",
        ),
        migrations.RemoveField(
            model_name="post",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="post",
            name="who_has",
        ),
        migrations.AddField(
            model_name="post",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("sales_id", models.AutoField(primary_key=True, serialize=False)),
                ("seller", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sales_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.post"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("purchase_id", models.AutoField(primary_key=True, serialize=False)),
                ("buyer", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.post"
                    ),
                ),
            ],
        ),
    ]
