# Generated by Django 4.1.2 on 2023-04-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_remove_post_is_buy_remove_post_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
    ]
