# Generated by Django 4.1.2 on 2023-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0030_remove_post_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="sales_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
